[workspace]
resolver = "2"
members = [
    "common",
    "contracts/pizza-contract",
    "delegates/pizza-delegate",
    "ui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# Serialization
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"

# Crypto
ed25519-dalek = { version = "2", features = ["serde", "rand_core"] }
blake3 = "1"
rand = { version = "0.8.5", features = ["getrandom"], default-features = true }

# Time
chrono = { version = "0.4", features = ["serde"] }

# Utils
thiserror = "1"
base64 = "0.22.1"
data-encoding = "2.3.3"
bs58 = "0.5.1"

# Freenet dependencies
freenet-scaffold = "0.2.1"
freenet-scaffold-macro = "0.2.1"
freenet-stdlib = { version = "0.1.35", features = ["contract"] }
