[package]
name = "pizza-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
ciborium.workspace = true
ed25519-dalek.workspace = true
chrono.workspace = true
thiserror.workspace = true
# Internal dependencies
freenet-scaffold.workspace = true
freenet-scaffold-macro.workspace = true
freenet-stdlib.workspace = true
rand.workspace = true
base64.workspace = true
data-encoding.workspace = true

[dev-dependencies]
serde_json = "1.0"
