[package]
name = "pizza-ui"
version.workspace = true
edition.workspace = true

[dependencies]
pizza-common = { path = "../common" }
freenet-stdlib = { workspace = true, features = ["net"] }

# UI Framework
dioxus = { version = "0.7", features = ["web"] }
dioxus-free-icons = { version = "0.10", features = ["font-awesome-solid", "font-awesome-regular"] }

# Async
futures = "0.3"
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.3", features = ["futures"] }

# Web
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Storage",
    "console",
    "Crypto",
    "Navigator",
    "Clipboard",
] }
wasm-bindgen = "0.2"
js-sys = "0.3"

# Serialization
serde.workspace = true
serde_json = "1"
ciborium.workspace = true

# Crypto
curve25519-dalek.workspace = true
x25519-dalek.workspace = true
# We can use rand_core in the UI crate because the wasm runs in a browser
ed25519-dalek = { workspace = true, features = ["rand_core"] }
rand = { version = "0.8", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }

# Time
chrono.workspace = true

# Utils
thiserror.workspace = true
log = "0.4"
console_log = "1"
console_error_panic_hook = "0.1"
