[application]
name = "pizza-ui"
default_platform = "web"

[web.app]
title = "Pizza Order Manager"

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource.dev]
style = ["assets/main.css"]

[web.resource.release]
style = ["assets/main.css"]
