name: Rust

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prebuild tailwind
      run: |
        nix develop --command npm --prefix ui install
        nix develop --command npm --prefix ui run build:css
    - name: Prebuild pizza-delegate
      run: nix develop --command cargo build --verbose --package pizza-delegate --target wasm32-unknown-unknown --release
    - name: Prebuild pizza-contract
      run: nix develop --command cargo build --verbose --package pizza-contract --target wasm32-unknown-unknown --release
    - name: Build
      run: nix develop --command cargo build --verbose --release
    - name: Run tests
      run: nix develop --command cargo test --verbose
    - name: Build UI with dioxus
      run: nix develop --command dx build --package pizza-ui --release
    - name: Upload pizza_contract.wasm
      uses: actions/upload-artifact@v4
      with:
        name: pizza_contract.wasm
        path: target/wasm32-unknown-unknown/release/pizza_contract.wasm
    - name: Upload pizza_delegate.wasm
      uses: actions/upload-artifact@v4
      with:
        name: pizza_delegate.wasm
        path: target/wasm32-unknown-unknown/release/pizza_delegate.wasm
    - name: Upload styles.css
      uses: actions/upload-artifact@v4
      with:
        name: styles.css
        path: ui/assets/styles.css
    - name: Upload UI dist
      uses: actions/upload-artifact@v4
      with:
        name: pizza-ui
        path: target/dx/pizza-ui/release/web/public

